services:
  airflow:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/tasks:/opt/airflow/tasks
      - ./airflow/data_clean:/opt/airflow/data_clean 
      - ./airflow/lstm_model:/opt/airflow/lstm_model
      - ./airflow/Bigquerykey.json:/opt/airflow/Bigquerykey.json
      - ./airflow/utils:/opt/airflow/utils
    environment:
      - PYTHONPATH=/opt/airflow

    depends_on:
      - mongodb
    
    command: airflow standalone
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: