services:
  airflow:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./tasks:/opt/airflow/tasks
      - ./data_clean:/opt/airflow/data_clean 
      - ./lstm_model:/opt/airflow/lstm_model
      - ./Bigquerykey.json:/opt/airflow/Bigquerykey.json
      - ./utils:/opt/airflow/utils
    environment:
      - PYTHONPATH=/opt/airflow

    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: